---
- name: Debian - Install apt-transport-https
  become: yes
  apt:
    name: apt-transport-https
    update_cache: yes
    state: present
  when: icingaweb2_manage_repository

- name: Debian - Add Icinga Web 2 repository key
  become: yes
  apt_key:
    url: "{{ icingaweb2_apt_key }}"
    state: present
  when: icingaweb2_manage_repository and icingaweb2_apt_key

- name: Debian - Add Icinga Web 2 repository
  become: yes
  apt_repository:
    repo: "{{ icingaweb2_apt_url }}"
    state: present
  when: icingaweb2_manage_repository

- name: Debian - Ensure Icinga Web 2 is installed
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ icingaweb2_packages }}"
  when: icingaweb2_manage_package

- name: Debian - Configure mysql databases
  become: yes
  ansible.builtin.mysql_db:
    login_unix_socket: "{{ mysqld_login_unix_socket }}"
    login_host: "{{ item.host }}"
    name: "{{ item.dbname }}"
    state: present
  loop: "{{ icingaweb2_resources.values() | list }}"
  when:
    - icingaweb2_manage_package
    - mysqld_login_unix_socket is defined
    - item.db == 'mysql'

- name: Debian - Configure mysql users
  community.mysql.mysql_user:
    login_unix_socket: "{{ mysqld_login_unix_socket }}"
    login_host: "{{ item.host }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
    priv: '{{ item.dbname }}.*:ALL'
  loop: "{{ icingaweb2_resources.values() | list }}"
  when:
    - icingaweb2_manage_package
    - mysqld_login_unix_socket is defined
    - item.db == 'mysql'

